### ISSUE TITLE
Showcase: Switch to tyk2 system throughout

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/ExampleNotebooks#104]
Currently the notebook bounces between benzene modifications in t4 and jnk1.  Instead use a tyk2 system throughout (to later link up with example results data)

**Comment by hannahbaumann** [comment]
Started working on this here: https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/117

Should we, similarly to the old showcase only setup one edge in the network, or just the entire network? I suggest doing the later since that's the normal use case.
