### ISSUE TITLE
showcase: include Ben's HREX gif?

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/ExampleNotebooks#115]
@RiesBen has a nice gif of HREX.  Can we include this in the showcase notebook?

**Comment by RiesBen** [comment]
If I remember this correctly, @IAlibay , @hannahbaumann  and I used this during talks. so the gif is around, but not living in a jnb.

Can this be closed? @jameseastwood

**Comment by IAlibay** [comment]
Including GIFs in notebooks is expensive, I second closing this.
