### ISSUE TITLE
Add bespokefit custom parameters example notebook

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/ExampleNotebooks#167]
Create an example notebook / cookbook which demonstrates how to use Bespokefit parameters with OpenFE.

**Comment by jthorton** [comment]
Ready for review https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/171

**Comment by jameseastwood** [comment]
Please make sure this gets added to the list of Example Notebooks that is built with the docs.

**Comment by IAlibay** [comment]
> Need to decide if this gets added to the list of Example Notebooks that is built with the docs.

I've added my comment on what needs doing in the PR - we really need a cookbook that is somewhat agnostic to whatever bespokefit does and just goes "here is some bespokefit output I baked beforehand", that's what we expose to our users the most. We can also have a tutorial that is more "here is an example of what you can do", but it has to come with all the warnings of "please go look at bespokefit's documentation, this is only for illustrative purposes".
