### ISSUE TITLE
Showcase notebook incorrectly says we can set box dimensions via the ChemicalSystem

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/ExampleNotebooks#181]
Follow up from https://github.com/OpenFreeEnergy/openfe/issues/1032

Section 2.3 says that you can set the box vectors when creating a ChemicalSystem. As far as I'm aware, this is incorrect. We should remove this to avoid confusing users.

**Comment by jameseastwood** [comment]
Mike pre-approves the PR to resolve this, so please feel free to merge without review
