### ISSUE TITLE
use separate repo for binder definition

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/ExampleNotebooks#31]
On reading the binder docs on why notebooks are slow to load, there's a section detailing how to use a separate repo to define the required environment. This can reduce the number of rebuilds required (as you don't rebuild for a commit in this content repo, only the binder env repo), which would increase our "uptime" and make more commits here less annoying (encouraging smaller fixes).

**Comment by dwhswenson** [comment]
I thought that @mikemhenry did something with building a container that was supposed to prevent the need to actually do that rebuild? That container build process is part of CI, and is significantly faster than running the tests (especially macOS).
